name = "slar-uptime-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"] # Run every minute

[[kv_namespaces]]
binding = "SLAR_CONFIG"
id = "replace-me-config-id"

[[kv_namespaces]]
binding = "SLAR_STATE"
id = "replace-me-state-id"

[vars]
SLAR_API_URL = "https://api.slar.app"
SLAR_API_TOKEN = "replace-me-token"
