{{- if and .Values.cloudflared.enabled (not .Values.cloudflared.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slar.fullname" . }}-cloudflared-token
  labels:
    {{- include "slar.labels" . | nindent 4 }}
type: Opaque
data:
  tunnel-token: {{ .Values.cloudflared.tunnelToken | b64enc | quote }}
{{- end }}
